
   Subscriptions of books as they appear in the Stephens 1550 TR Greek Text
                 (included in the Online Bible Greek format)

   No subscription exists for Matthew, John, Acts, 2 Peter, or Revelation.

[ to kata markon euaggelion ]
[ to kata loukan euaggelion ]
[ prov rwmaiouv egrafh apo korinyou dia foibhv thv diakonou thv
    en kegcreaiv ekklhsiav ]
[ prov korinyiouv prwth egrafh apo filippwn dia stefana kai
    fourtounatou kai acaikou kai timoyeou ]
[ prov korinyiouv deutera egrafh apo filippwn thv makedoniav
    dia titou kai louka ]
[ prov galatav egrafh apo rwmhv ]
[ prov efesiouv egrafh apo rwmhv dia tucikou ]
[ prov filipphsiouv egrafh apo rwmhv di epafroditou ]
[ prov kolassaeiv egrafh apo rwmhv dia tucikou kai onhsimou ]
[ prov yessalonikeiv prwth egrafh apo ayhnwn ]
[ prov yessalonikeiv deutera egrafh apo ayhnwn ]
[ prov timoyeon prwth egrafh apo laodikeiav htiv estin mhtropoliv
    frugiav thv pakatianhv ]
[ prov timoyeon deutera thv efesiwn ekklhsiav prwton episkopon
    ceirotonhyenta egrafh apo rwmhv ote ek deuterou paresth
    paulov tw kaisari nerwni ]
[ prov titon thv krhtwn ekklhsiav prwton episkopon ceirotonhyenta
    egrafh apo nikopolewv thv makedoniav ]
[ prov filhmona egrafh apo rwmhv dia onhsimou oiketou ]
[ prov ebraiouv egrafh apo thv italiav dia timoyeou ]
[ iakwbou epistolh ]
[ petrou epistolh kayolikh prwth ]
[ iwannou espistolh kayolikh prwth ]
[ iwannou espistolh deutera ]
[ iwannou epistolh kayolikh trith ]
[ epistolh iouda kayolikh ]
